# Copyright (c) 2016 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Arcadia Analytics Wiki
site_description: Documentation for Arcadia Analytics
site_author: 
site_url: http://docs.arcadiaanalytics.com

# Repository
repo_name: GitHub
repo_url: https://github.com/arcadia/analytics-doc

# Copyright
copyright: Copyright (c) 2016 Arcadia Healthcare Solutions

# Documentation and theme
theme_dir: material

# Options
extra:
  version: 4.11
  logo: images/Mountain_64.png
  author:
    github: arcadia
    twitter: ArcadiaHealthIT

# Extensions
markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '#'

# Page tree
# pages:
#   - Material: index.md
#   - Getting started: getting-started.md
#   - Customization: customization.md
#   - License: license.md